# I-need-help-on-it-i-dont-know-about-codes-at-all
&lt;?xml version="1.0" ?>&lt;root> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:44&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare6hrs'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:44&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Petsitter24'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:44&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:Interactions_Solo_GoToRabbitHole_PlasticSurgery_+20SP  "Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:NPCDrama_SimGivingBirth_AtHospital "Away Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Acquaintances'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Roll'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Petsitter12'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Heel'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole60'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Crush'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_ArtExhibition'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Friends_Family'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Hiking'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_FightAgainstBullying "Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_VisitGynecologist_Abortion_Continue'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Date'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Church'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole_NPC30'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Speak'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:45&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_sit'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:Interactions_Solo_GoToRabbitHole_SocialDramaClass  "Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_TechMuseum'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare4hrs'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole120'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_FightAgainstDomesticAbuse "Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Petsitter'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare8hrs'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Fetch'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.roommateNPC_Rabbithole_Absent'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Petsitter8'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Circus'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_lieDown'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainerOwner_Continue'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_PlayDead'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:46&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare2hrs'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:NPCDrama_SimGivingBirth_AtHospital_NPC "Away Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_CookingContest'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_DogTrainer_Shake'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_VisitGynecologist_SigOther'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.roommateNPC_Rabbithole_GoEat'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_ReadMeet'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_VisitGynecologist'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Friends'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_FightAgainstAnimalAbuse "Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:47&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole_NPC60'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_SupportTheLGBTQA+Community "Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_MiniVacation'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Honeymoon'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.roommateNPC_Rabbithole'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_Daycare10hrs'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole30'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:Interactions_Solo_GoToRabbitHole_PlasticSurgery_+20SP_Continuation  "Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_RockConcert'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LittleMsSam:si_Visit_GoforAWalkWithRabbitHole_NPC120'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;report>&lt;version>2&lt;/version>&lt;sessionid>8c861afd92cfbff7605bc40e&lt;/sessionid>&lt;type>desync&lt;/type>&lt;sku>ea.maxis.sims4_64.15.pc&lt;/sku>&lt;createtime>2021-03-24 16:03:48&lt;/createtime>&lt;buildsignature>Local.Unknown.Unknown.1.72.28.1030-1.200.000.495.Release&lt;/buildsignature>&lt;categoryid>interaction.py:1965&lt;/categoryid>&lt;desyncid>8c861afd92cfbff7605bc40e&lt;/desyncid>&lt;systemconfig/>&lt;screenshot/>&lt;desyncdata>[manus] Exception in &amp;lt;class 'sims4.tuning.instances.LD:Interactions_Solo_SocialHelper_GoToRabbitHole_FightAgainstRacism "Super Interaction"'&amp;gt;._tuning_loaded_callback. (AttributeError: 'str' object has no attribute 'factory')&amp;#13;&amp;#10;Traceback (most recent call last):&amp;#13;&amp;#10;&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 154, in c_api_server_init_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\core_services.py", line 164, in start_service_tick&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 331, in start_single_service&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 156, in update_incremental_start&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 215, in _execute_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\tuning\instance_manager.py", line 602, in invoke_registered_callbacks_gen&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 1994, in _tuning_loaded_callback&amp;#13;&amp;#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 1965, in _tuning_loaded_callback&amp;#13;&amp;#10;AttributeError: 'str' object has no attribute 'factory'rtim=0&amp;#13;&amp;#10;Client Session Time: 247.55&amp;#13; &amp;#10;Num Save Errors: 0&amp;#13; &amp;#10;Num Load Errors: 0&amp;#13; &amp;#10;Current Game State: 0x96d01090&amp;#13; &amp;#10;Origin Version: 10,5,95,47231&amp;#13; &amp;#10;Modded: True&amp;#13; &amp;#10;SystemInfo: Windows 10 10.0.19042 GPU: NVIDIA GeForce GTX 1060 nvldumdx.dll 26.21.14.4223, GUID: D7B71E3E-5F60-11CF-EA63-6D321BC2D735&amp;#13; &amp;#10;&lt;/desyncdata>&lt;/report> &lt;/root>
